#!/bin/bash

theme=aptosid-void
res=1920x1200
anim=_anim

./svg-anim.pl streaked-fred.svg 30 streaked-fred$anim.svg scaley,0.25:1,1:30,sin:middle opacity,0:1,1:30,sin
inkscape --without-gui --export-png="streaked-fred$anim.png" streaked-fred$anim.svg
rm streaked-fred$anim.svg

./svg-anim.pl unstreaked-fred.svg 30 unstreaked-fred$anim.svg opacity,0:1,1:30,sin
inkscape --without-gui --export-png="unstreaked-fred$anim.png" unstreaked-fred$anim.svg
rm unstreaked-fred$anim.svg

./composite_pngs.pl -o $theme/$res/fred.png streaked-fred$anim.png unstreaked-fred$anim.png
rm streaked-fred$anim.png unstreaked-fred$anim.png
